- hosts: webserver
  become: yes
  collections:
    - community.docker
  tasks:
    - name: Update apt packages
      apt:
        update_cache: yes

    - name: Install required packages
      apt:
        name: ["docker.io", "docker-compose"]
        state: present

    - name: Start Docker service
      service:
        name: docker
        state: started
        enabled: yes

    - name: Pull app image from DockerHub
      community.docker.docker_image:
        name: lauraokafor/nanoimg:latest
        source: pull

    - name: Run app container
      community.docker.docker_container:
        name: myapp
        image: lauraokafor/nanoimg:latest
        state: started
        restart_policy: always
        published_ports:
          - "80:80"

